services:
  db:
    image: mysql:8.0
    container_name: govsmart_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: govsmart
      MYSQL_USER: govsmart_user
      MYSQL_PASSWORD: govsmart_password
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      timeout: 20s
      retries: 10

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: govsmart_backend
    restart: always
    ports:
      - "8000:8000"
    environment:
      - MYSQL_USER=govsmart_user
      - MYSQL_PASSWORD=govsmart_password
      - MYSQL_HOST=db
      - MYSQL_PORT=3306
      - MYSQL_DB=govsmart
      - SECRET_KEY=supersecretkeygovsmart2026!
      - ACCESS_TOKEN_EXPIRE_MINUTES=1440
    volumes:
      # Volume persisten untuk foto bukti upload (maks 5 MB per file sesuai PRD)
      - uploads_data:/app/uploads
    depends_on:
      db:
        condition: service_healthy

volumes:
  mysql_data:
  uploads_data:

